@startuml class diagram
frame "cd: pyzefir model" {
class Generator
class Network
EnergySource <|---- Generator
EnergySource <|---- Storage
Network *---- Generator
Network *---- Storage
Network *----- Bus
abstract class EnergySource
}
@enduml
